language: java
notifications:
  email:
    on_success: change  # When failure -> success
    on_failure: change  # When success -> failure
jobs:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk12
  - os: osx
    osx_image: xcode11

