sudo: false

dist: xenial

language: java

jdk: openjdk12

deploy:
    provider: releases
    api_key:
      secure: "$GITHUB_OAUTH_TOKEN"
    skip_cleanup: true
    file_glob: true
    file: target/koord-*-jar-with-dependencies.jar
    tag_name: $TRAVIS_TAG  # Add tag name to overwrite properly
    draft: true
    overwrite: true
    on:
        repo: cyphyhouse/KoordLanguage
        branch: master
        tags: true  # Only delpoy when the commit is tagged
